---
name: "phone-logger"
description: "Phone number resolver with Fritz!Box Callmonitor integration"
url: "https://github.com/akentner/phone-logger"
version: "0.1.3"
slug: "phone-logger"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8080
panel_icon: "mdi:phone-log"
panel_title: "Phone Logger"
homeassistant_api: true
map:
  - type: addon_config
    path: /addons_config/phone-logger
options:
  log_level: "INFO"
  phone_country_code: "49"
  phone_local_area_code: ""
  fritz_host: "192.168.178.1"
  fritz_port: 1012
  input_adapters:
    - type: "fritz"
      name: "fritz"
      enabled: true
    - type: "rest"
      name: "rest"
      enabled: true
    - type: "mqtt"
      name: "mqtt"
      enabled: false
  resolver_adapters:
    - type: "json_file"
      name: "json_file"
      enabled: true
    - type: "sqlite"
      name: "sqlite"
      enabled: true
    - type: "tellows"
      name: "tellows"
      enabled: true
    - type: "dastelefon"
      name: "dastelefon"
      enabled: true
    - type: "klartelbuch"
      name: "klartelbuch"
      enabled: false
  output_adapters:
    - type: "call_log"
      name: "call_log"
      enabled: true
    - type: "webhook"
      name: "HA Webhook"
      enabled: false
    - type: "mqtt"
      name: "mqtt"
      enabled: false
  webhooks:
    - url: ""
      token: ""
      events:
        - ring
        - call
        - connect
        - disconnect
  mqtt_broker: "homeassistant"
  mqtt_topic_prefix: "phone-logger"
schema:
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  phone_country_code: str
  phone_local_area_code: str?
  fritz_host: str
  fritz_port: port
  input_adapters:
    - type: str
      name: str
      enabled: bool
  resolver_adapters:
    - type: str
      name: str
      enabled: bool
  output_adapters:
    - type: str
      name: str
      enabled: bool
  webhooks:
    - url: url?
      token: password?
      events:
        - str?
  mqtt_broker: str?
  mqtt_topic_prefix: str?
